### ISSUE TITLE
main.js - Filter problem - error when only "Reversals" is selected

### ISSUE THREAD

**Issue by michaeljoelt** [michaeljoelt/tarot#12]
When just "Reversals" is selected (or nothing), a card cannot be drawn since there are no cards in the deck. The following error shows in console:
```
main.js:29 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at HTMLInputElement.selectCard (main.js:29:30)
```

Suggestions for fixing:
- in selectCard(): after getting the filtered deck, only continue the function if deck.length is > 0 (I believe you can break out of a function using "return")
- before breaking out of the function, it also might be nice to inform the user that they cannot draw a card from an empty deck, and that they should review their filter

**Comment by michaeljoelt** [comment]
yes, please! assigning to you

**Comment by ashinsabu** [comment]
Hey would you like the error message to be displayed as a window alert or inside the HTML document inside some kind of a div or tag?

**Comment by michaeljoelt** [comment]
good question.. as a user I prefer when it's directly in the dom, instead of alert boxes these days. what do you think? I'm fine with either

**Comment by ashinsabu** [comment]
Got it! I'd prefer the error displayed inside the dom as well. I'll go ahead with that.

**Comment by michaeljoelt** [comment]
merged changes to main

**Comment by ashinsabu** [comment]
👍
