### ISSUE TITLE
style.css - mobile compatibility 

### ISSUE THREAD

**Issue by michaeljoelt** [michaeljoelt/tarot#13]
tested on mobile device and was a pretty bad user experience. needs testing and media query work

**Comment by ashinsabu** [comment]
I am interested in trying to fix this.

**Comment by michaeljoelt** [comment]
go for it! thanks for checking in. feel free to reach out here or in the Discussions tab if you run in to any issues you want to brainstorm with others.

**Comment by ashinsabu** [comment]
Should I go ahead with fixing these listed issues?

**Comment by michaeljoelt** [comment]
So sorry - I thought I responded earlier. 
Yes, go for it! I agree with the issues you've found, and also can't currently think of any more related to mobile CSS. 
Thanks for the great communication!

**Comment by ashinsabu** [comment]
I've added some media queries to fix the given issues. Please do list any other changes you'd like to see.
![image](https://user-images.githubusercontent.com/38109596/174268330-55706375-8b20-4c56-a74e-05b6320352df.png)
![image](https://user-images.githubusercontent.com/38109596/174268388-7627044f-e80d-46ab-9c7d-bd7addfc651b.png)

If not I'll create the PR.

**Comment by ashinsabu** [comment]
👍
