### ISSUE TITLE
index.html / main.js - update filter options

### ISSUE THREAD

**Issue by michaeljoelt** [michaeljoelt/tarot#14]
need to simplify filter options to only include "reversals" and "major arcana". other options are not common for most users (maybe can be included as "advanced" filter features later or something)

index.html - need to remove the options related to "swords", "pentacles", "cups", and "wands"

main.js - I think this is the only piece of code to remove here:
```
|| userFilter.includes(card.suit)
```

**Comment by nikhilnarla** [comment]
Hi @michaeljoelt I am interested to work on this. Could you please assign it to me?

**Comment by michaeljoelt** [comment]
yesss.. though now I'm interested in there being a "Filter" button that can hide/show the curren filter's fieldset element. is that something you could help with? please feel free to reach out here or in the Discussions tab if there's anything you want to brainstorm too!

**Comment by michaeljoelt** [comment]
I'm actually still good with the original plan of just removing these extra options for now; so whatever you prefer working on if you're still down!
